### ISSUE TITLE
release version log4qt Memory leak(OS:Windows)

### ISSUE THREAD

**Issue by wslj2016** [MEONMedical/Log4Qt#60] opened 2021-10-13 01:37 UTC
The released project occupies more memory with the increase of logs，and not released.
The more debug or error log info taked ,the more memory will be occupied, but there is no phenomenon in the debug version.

**Comment by wslj2016** [comment] 2021-10-13 03:11
I just tried it under ubuntu, and the files generated by release and debug have no memory leaks.

**Comment by wslj2016** [comment] 2021-10-13 08:10
anyone help

**Comment by andibacher** [comment] 2021-11-09 14:48
How did you notice this ? TaskManager? I tried to reproduce this on Windows in Release Mode (also in Debug). And I can not notice any memory increase over the time. I modified the basis example so that it does continuous logging. 

Do you have more information under which conditions this happens?

**Comment by wslj2016** [comment] 2021-12-05 01:28
Thank you for your repay,I just notice that with TaskManager.
I also tried the version of the official website(https://sourceforge.net/projects/log4qt/files/),which also has this phenomenon(memory leak only in the release mode of windows OS).

**Comment by andibacher** [comment] 2022-01-01 20:14
Sorry I don't see this here an Windows and release mode, even if the modified basic example does continuous logging over some hours. I don't see were a memory leak in log4qt should happen.

**Comment by andibacher** [comment] 2022-03-21 09:56
I close this issue because I can not reproduce this.

We use log4qt in several projects on windows and we never have notice an significant memory increase over time.

**Closed by andibacher** 2022-03-21 09:56 UTC

**Comment by yangyongzhen** [comment] 2022-07-27 04:29
i have the same probloems,The more debug or error log info taked ,the more memory will be occupied in windows.
i have the examples used by qt project, you can try int
![image](https://user-images.githubusercontent.com/8438899/181161705-f072823f-aa42-431b-b47b-c95e6838e67c.png)
